import matplotlib.pyplot as plt
import pandas as pd

# Read data from file generated by Kotlin
data = []
with open('/home/abade/Documents/Programas/PAA/PAA_Algorithms/graph_data.txt', 'r') as f:
    for line in f.readlines()[1:]:  # Skip header
        if line.strip():
            n, moves, comparisons, time_ms = line.strip().split('\t')
            if moves != '-':  # Only include valid data
                data.append({
                    'n': int(n),
                    'movimentos': int(moves),
                    'comparacoes': int(comparisons),
                    'tempo_ms': float(time_ms)
                })

df = pd.DataFrame(data)

# Create only 3 graphs as requested
fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(18, 6))

# Graph 1: n × Moves
ax1.plot(df['n'], df['movimentos'], 'bo-', linewidth=2, markersize=8)
ax1.set_xlabel('Dimensão do Tabuleiro (n)', fontsize=12)
ax1.set_ylabel('Número de Movimentações', fontsize=12)
ax1.set_title('n × Movimentações', fontsize=14, fontweight='bold')
ax1.grid(True, alpha=0.3)

# Graph 2: n × Comparisons
ax2.plot(df['n'], df['comparacoes'], 'ro-', linewidth=2, markersize=8)
ax2.set_xlabel('Dimensão do Tabuleiro (n)', fontsize=12)
ax2.set_ylabel('Número de Comparações', fontsize=12)
ax2.set_title('n × Comparações', fontsize=14, fontweight='bold')
ax2.grid(True, alpha=0.3)

# Graph 3: n × Time
ax3.plot(df['n'], df['tempo_ms'], 'go-', linewidth=2, markersize=8)
ax3.set_xlabel('Dimensão do Tabuleiro (n)', fontsize=12)
ax3.set_ylabel('Tempo (ms)', fontsize=12)
ax3.set_title('n × Tempo', fontsize=14, fontweight='bold')
ax3.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('knight_tour_analysis.png', dpi=300, bbox_inches='tight')
plt.show()

# Generate results table
print("="*80)
print("TABELA DE RESULTADOS - PASSEIO DO CAVALO")
print("="*80)
print(f"{'n':<5} {'Movimentações':<15} {'Comparações':<15} {'Tempo (ms)':<12}")
print("-"*80)

for _, row in df.iterrows():
    print(f"{row['n']:<5} {row['movimentos']:<15} {row['comparacoes']:<15} {row['tempo_ms']:<12.2f}")

print("="*80)
